/* ============================================
   假面骑士英雄档案 - 数据层
   ============================================ */

const allRiders = [
  // ==================== 昭和骑士 ====================
  {
    id: 1, name: "假面骑士1号", nameEn: "Kamen Rider 1", category: "showa",
    era: "昭和 · 1971", debut: 1971,
    height: "180cm", weight: "70kg",
    punchPower: "60t", kickPower: "90t",
    jumpPower: "25m", runSpeed: "100m/3.5s",
    humanHost: "本乡猛", homePlanet: "地球",
    transformationItem: "台风腰带",
    color: "#33cc33", colorSecondary: "#cc0000",
    abilities: ["Rider Kick", "Rider Punch", "Rider Chop", "Rider Jump", "台风回旋"],
    description: `假面骑士系列的开山之作。本乡猛被邪恶组织修卡改造为蝗虫怪人，在脑改造前逃脱，从此化身为守护人类自由与和平的假面骑士1号。以蝗虫为原型，拥有绿色复眼和红色围巾，骑着改造摩托车驰骋战场。`,
    story: `1971年，天才科学家本乡猛被修卡组织绑架并改造为蝗虫怪人。在脑改造即将完成之际，被绿川博士所救，逃脱修卡基地。此后，本乡猛以假面骑士的身份与修卡战斗，保护人类的自由。他的战斗风格以Rider Kick为核心，配合旋风号摩托车的高速机动，成为所有假面骑士的原点。`
  },
  {
    id: 2, name: "假面骑士2号", nameEn: "Kamen Rider 2", category: "showa",
    era: "昭和 · 1971", debut: 1971,
    height: "172cm", weight: "65kg",
    punchPower: "55t", kickPower: "85t",
    jumpPower: "23m", runSpeed: "100m/4.0s",
    humanHost: "一文字隼人", homePlanet: "地球",
    transformationItem: "台风腰带",
    color: "#2db82d", colorSecondary: "#cc0000",
    abilities: ["Rider Kick", "Rider Punch", "Rider Chop", "Rider Jump"],
    description: `假面骑士2号是本乡猛的继承者。自由摄影师一文字隼人被修卡绑架改造，后被1号救出，成为第二位假面骑士。与1号并肩作战，共同对抗修卡的邪恶计划。`,
    story: `一文字隼人是一名自由摄影师，被修卡抓走后改造为假面骑士2号。他的战斗力与1号不相上下，在与修卡的战斗中展现了惊人的毅力。当1号前往海外作战时，2号负责守护日本。两人交替出场，为系列奠定了双主角的基础。`
  },
  {
    id: 3, name: "假面骑士V3", nameEn: "Kamen Rider V3", category: "showa",
    era: "昭和 · 1973", debut: 1973,
    height: "180cm", weight: "78kg",
    punchPower: "90t", kickPower: "110t",
    jumpPower: "60m", runSpeed: "100m/1.6s",
    humanHost: "风见志郎", homePlanet: "地球",
    transformationItem: "双重台风腰带",
    color: "#33cc33", colorSecondary: "#ffffff",
    abilities: ["V3 Kick", "V3 Thunder", "V3回转Kick", "Double Typhoon", "26种秘密"],
    description: `假面骑士V3是1号和2号的后辈，拥有两人力量的强化骑士。风见志郎目睹家人被迪斯特龙杀害，主动请求1号和2号将其改造，继承了两位前辈的力量，拥有26个秘密技能。`,
    story: `风见志郎的家人惨遭迪斯特龙杀害，他决心复仇并保护他人。1号和2号在危急时刻将志郎改造为假面骑士V3，融合了两位骑士的力量。V3拥有双重台风腰带，可以施展26种不同技能，战斗力远超前辈。`
  },
  {
    id: 4, name: "假面骑士X", nameEn: "Kamen Rider X", category: "showa",
    era: "昭和 · 1974", debut: 1974,
    height: "178cm", weight: "70kg",
    punchPower: "75t", kickPower: "90t",
    jumpPower: "60m", runSpeed: "100m/2.0s",
    humanHost: "神敬介", homePlanet: "地球",
    transformationItem: "水星回路",
    color: "#cc0000", colorSecondary: "#c0c0c0",
    abilities: ["X Kick", "X Punch", "水星之力", "Ridol棍法", "深海作战"],
    description: `假面骑士X是以海洋和水星力量为主题的骑士。神敬介被GOD机关杀害后，在父亲改造下复活为假面骑士X。擅长使用武器Ridol棍战斗，可切换多种形态，适应水陆空三栖作战。`,
    story: `神敬介在与GOD机关的战斗中牺牲，其科学家父亲将他改造为假面骑士X。X骑士拥有水星的力量，可在深海自由活动。他的专属武器Ridol棍可以变成棍、枪、鞭等多种形态。他是首个以武器为特色的假面骑士。`
  },
  {
    id: 5, name: "假面骑士Amazon", nameEn: "Kamen Rider Amazon", category: "showa",
    era: "昭和 · 1974", debut: 1974,
    height: "175cm", weight: "62kg",
    punchPower: "80t", kickPower: "100t",
    jumpPower: "80m", runSpeed: "100m/2.0s",
    humanHost: "山本大介", homePlanet: "地球(亚马逊)",
    transformationItem: "基基之腕",
    color: "#cc0000", colorSecondary: "#ff6600",
    abilities: ["大切断", "野性撕咬", "Jaguar Shock", "Amazon Kick", "丛林追踪"],
    description: `假面骑士Amazon是野性最强的骑士。山本大介在亚马逊丛林中长大，接受了古代印加文明的改造，变身为以蜥蜴为原型的Amazon。战斗风格原始狂野，不讲章法但极其凶猛。`,
    story: `山本大介年幼时因飞机失事流落亚马逊丛林，在印加部落中长大。当邪恶组织入侵丛林时，大介接受了古代改造手术，成为假面骑士Amazon。他的战斗方式狂野不羁，标志性招式大切断能一击撕裂敌人。`
  },
  {
    id: 6, name: "假面骑士Stronger", nameEn: "Kamen Rider Stronger", category: "showa",
    era: "昭和 · 1975", debut: 1975,
    height: "183cm", weight: "78kg",
    punchPower: "100t", kickPower: "120t",
    jumpPower: "100m", runSpeed: "100m/1.2s",
    humanHost: "城茂", homePlanet: "地球",
    transformationItem: "电击腰带",
    color: "#cc0000", colorSecondary: "#ffcc00",
    abilities: ["Stronger电Kick", "超电磁力量", "Charge Up", "电气风暴", "55吨拳力"],
    description: `假面骑士Stronger是最强之名的骑士。城茂主动潜入Black Satan接受改造，以电气力量为核心，能够进行Charge Up强化形态。他是昭和骑士中首个拥有强化变身能力的骑士。`,
    story: `城茂为了替死去的好友复仇，主动潜入Black Satan接受改造手术。凭借坚强意志，他获得了电气超人般的力量。Stronger可以吸收电能强化自己，Charge Up后全身变为银白色，战斗力和防御力大幅提升。`
  },
  {
    id: 7, name: "假面骑士Skyrider", nameEn: "Skyrider", category: "showa",
    era: "昭和 · 1979", debut: 1979,
    height: "180cm", weight: "70kg",
    punchPower: "80t", kickPower: "100t",
    jumpPower: "200m", runSpeed: "100m/1.8s",
    humanHost: "筑波洋", homePlanet: "地球",
    transformationItem: "龙卷风腰带",
    color: "#33cc33", colorSecondary: "#ffcc00",
    abilities: ["Sky Kick", "Sailing Jump", "龙卷风飞行", "99种技能", "天空作战"],
    description: `假面骑士Skyrider以天空飞行为特色。筑波洋被新修卡改造后，在逃脱中获得飞行能力。拥有99种技能，擅长空中战斗，跳跃力和飞行能力在昭和骑士中首屈一指。`,
    story: `筑波洋在一次意外中被新修卡改造，虽然失去了记忆但保留了正义之心。Skyrider的腰带拥有龙卷风之力，可以让他自由飞行。他接受了1号至Stronger共7位前辈的特训，最终掌握99种技能，成为一名全能骑士。`
  },
  {
    id: 8, name: "假面骑士Super-1", nameEn: "Kamen Rider Super-1", category: "showa",
    era: "昭和 · 1980", debut: 1980,
    height: "185cm", weight: "75kg",
    punchPower: "100t", kickPower: "120t",
    jumpPower: "150m", runSpeed: "100m/1.0s",
    humanHost: "冲一也", homePlanet: "地球",
    transformationItem: "宇宙开发用变身腕轮",
    color: "#cc0000", colorSecondary: "#3366ff",
    abilities: ["Super Kick", "五能手甲", "雷神拳", "冷热拳", "重力拳"],
    description: `假面骑士Super-1是宇宙开发用改造人。冲一也自愿接受改造，成为在宇宙环境中也能活动的超级战士。双手装备可更换的五能手甲，适应各种战斗环境。`,
    story: `冲一也是一名宇航员，为了人类的宇宙开发事业自愿接受改造。Super-1拥有五能手甲系统：银手甲（标准）、雷神手甲（雷电）、冷热手甲（温度）、重力手甲（重力操控）、光芒手甲（闪光），每种手甲都有独特的战斗能力。`
  },
  {
    id: 9, name: "假面骑士ZX", nameEn: "Kamen Rider ZX", category: "showa",
    era: "昭和 · 1984", debut: 1984,
    height: "185cm", weight: "78kg",
    punchPower: "120t", kickPower: "150t",
    jumpPower: "80m", runSpeed: "100m/0.6s",
    humanHost: "村雨良", homePlanet: "地球",
    transformationItem: "生化腰带",
    color: "#33cc33", colorSecondary: "#c0c0c0",
    abilities: ["ZX Kick", "ZX Punch", "手里剑攻击", "忍者战斗术", "极限速度"],
    description: `假面骑士ZX是昭和时代的第十位骑士，以忍者为主题。村雨良被巴丹帝国改造为改造人士兵，但在姐姐的呼唤下恢复记忆。拥有超越前9位骑士的速度和忍者战斗技巧。`,
    story: `村雨良与姐姐被巴丹帝国抓走进行改造实验。改造后的良成为了完美的改造人战士ZX。在姐姐的牺牲和呼唤下，良恢复了记忆。ZX结合了忍术与现代科技，忍者般的灵活身手加上超高速移动能力，使他成为最敏捷的骑士。`
  },
  {
    id: 10, name: "假面骑士Black", nameEn: "Kamen Rider Black", category: "showa",
    era: "昭和 · 1987", debut: 1987,
    height: "198.7cm", weight: "87kg",
    punchPower: "120t", kickPower: "200t",
    jumpPower: "140m", runSpeed: "100m/1.2s",
    humanHost: "南光太郎", homePlanet: "地球",
    transformationItem: "帝王石腰带",
    color: "#111111", colorSecondary: "#cc0000",
    abilities: ["Rider Punch", "Rider Kick", "帝王石闪光", "战斗蝗虫号", "世纪王之力"],
    description: `假面骑士Black是世纪王黑日，拥有帝王石的力量。南光太郎与兄弟秋月信彦在出生时被戈尔戈姆选中，被植入帝王石。光太郎被改造为世纪王黑日，但他选择为正义而战。`,
    story: `南光太郎与秋月信彦在19岁生日时被戈尔戈姆劫持，经过改造后分别成为世纪王黑日和世纪王影月。光太郎在记忆尚存时逃脱，化身为假面骑士Black。他拥有帝王石的强大力量，骑着战斗蝗虫号驰骋战场。Black的故事开启了假面骑士的文艺复兴。`
  },
  {
    id: 11, name: "假面骑士Black RX", nameEn: "Kamen Rider Black RX", category: "showa",
    era: "昭和 · 1988", debut: 1988,
    height: "198.8cm", weight: "88kg",
    punchPower: "140t", kickPower: "220t",
    jumpPower: "160m", runSpeed: "100m/0.8s",
    humanHost: "南光太郎", homePlanet: "地球",
    transformationItem: "太阳之子腰带",
    color: "#33cc33", colorSecondary: "#111111",
    abilities: ["RX Kick", "Revolcane光剑", "太阳之力", "悲痛形态", "生化形态"],
    description: `假面骑士Black RX是Black的进化形态。南光太郎在太阳之力的照射下重生为RX，拥有切换形态的能力。悲痛形态（机械骑士）和生化形态（生化骑士）分别代表不同的战斗风格。`,
    story: `在击败戈尔戈姆后，南光太郎被克莱西斯帝国袭击。濒死之际，太阳的力量注入体内，Black进化为Black RX。RX不仅拥有更强的力量和速度，还能根据战况切换形态：以枪械为主的机械骑士形态，以及液体化能力的生化骑士形态。`
  },

  // ==================== 平成骑士 ====================
  {
    id: 12, name: "假面骑士空我", nameEn: "Kamen Rider Kuuga", category: "heisei",
    era: "平成 · 2000", debut: 2000,
    height: "200cm", weight: "99kg",
    punchPower: "3t", kickPower: "10t",
    jumpPower: "15m", runSpeed: "100m/5.2s",
    humanHost: "五代雄介", homePlanet: "地球",
    transformationItem: "亚古鲁腰带",
    color: "#cc0000", colorSecondary: "#ffcc00",
    abilities: ["Mighty Kick", "形态切换", "金色力量", "Rising形态", "Amazing Ultimate"],
    description: `假面骑士空我是平成假面骑士系列的开山之作。五代雄介发现了古代战士空我的腰带，变身为空我。可以切换青龙、天马、泰坦等多种形态，战斗方式灵活多变。`,
    story: `冒险家五代雄介在遗迹中发现了古代战士空我的腰带。当未确认生命体古朗基开始袭击人类时，雄介戴上腰带变身空我。从白色初生形态到红色全能形态，再到金色升华形态，空我的力量不断觉醒。最终形态惊异全能拥有毁灭性的力量。空我开创了平成骑士的多形态路线。`
  },
  {
    id: 13, name: "假面骑士AgitΩ", nameEn: "Kamen Rider Agito", category: "heisei",
    era: "平成 · 2001", debut: 2001,
    height: "195cm", weight: "95kg",
    punchPower: "7t", kickPower: "15t",
    jumpPower: "30m", runSpeed: "100m/5.0s",
    humanHost: "津上翔一", homePlanet: "地球",
    transformationItem: "Alter Ring",
    color: "#cc0000", colorSecondary: "#ffcc00",
    abilities: ["Rider Kick", "Burning Form", "Shining Form", "Storm Form", "Flame Form"],
    description: `假面骑士AgitΩ继承了空我的世界观。津上翔一在一次神秘事件后失去记忆，却获得了变身AgitΩ的能力。拥有多种形态进化，最终形态闪耀形态拥有超越人类理解的光之力。`,
    story: `津上翔一在一艘漂流船上被发现，完全失去记忆。随着未知生命体袭击人类，翔一发现自己可以变身为AgitΩ。随着战斗的深入，他的力量不断进化：大地形态、暴风形态、火焰形态、三位一体形态、燃烧形态，最终进化为闪耀形态。AgitΩ的名字意为觉醒。`
  },
  {
    id: 14, name: "假面骑士龙骑", nameEn: "Kamen Rider Ryuki", category: "heisei",
    era: "平成 · 2002", debut: 2002,
    height: "190cm", weight: "90kg",
    punchPower: "10t", kickPower: "20t",
    jumpPower: "35m", runSpeed: "100m/5.0s",
    humanHost: "城户真司", homePlanet: "地球",
    transformationItem: "V带扣+龙骑卡组",
    color: "#cc0000", colorSecondary: "#111111",
    abilities: ["Final Vent", "龙之吐息", "Drag Saber", "Strike Vent", "镜世界穿梭"],
    description: `假面骑士龙骑开创了多骑士大战的先河。城户真司是一名实习记者，偶然获得龙骑卡组后卷入镜世界的骑士战争。契约兽为无双龙Dragreder，通过卡片发动各种技能。`,
    story: `城户真司被卷入镜世界的骑士战争。在这座镜子中的异世界里，13位假面骑士需要互相战斗，最终胜利者可以实现任何愿望。真司拒绝战斗，他试图阻止骑士间的残杀。但在残酷的现实面前，他不得不战斗以保护无辜者。龙骑以战斗才能活下去为核心主题，结局震撼人心。`
  },
  {
    id: 15, name: "假面骑士Faiz", nameEn: "Kamen Rider Faiz (555)", category: "heisei",
    era: "平成 · 2003", debut: 2003,
    height: "186cm", weight: "91kg",
    punchPower: "2.5t", kickPower: "5t",
    jumpPower: "35m", runSpeed: "100m/5.8s",
    humanHost: "乾巧", homePlanet: "地球",
    transformationItem: "Faiz Phone + Faiz Driver",
    color: "#33cc33", colorSecondary: "#ffff00",
    abilities: ["Crimson Smash", "Axel Form", "Blaster Form", "Faiz Shot", "光子血液"],
    description: `假面骑士Faiz以科技感十足的设计闻名。乾巧是一个流浪青年，意外获得Faiz腰带后成为假面骑士。腰带实际上是Orphnoch（奥尔菲诺克）使用的装备，剧情中人与怪物的界限模糊。`,
    story: `乾巧是一名四处游荡的青年，捡到了Faiz腰带。但他不是被选中的人，这条腰带是智脑公司为Orphnoch开发的战士系统。巧以人类之躯使用腰带，承受着巨大负担。加速形态可以短暂获得超高速，爆裂形态则是最强的火力全开。Faiz的故事探讨了人与非人的边界。`
  },
  {
    id: 16, name: "假面骑士Blade", nameEn: "Kamen Rider Blade", category: "heisei",
    era: "平成 · 2004", debut: 2004,
    height: "200cm", weight: "101kg",
    punchPower: "2.8t", kickPower: "4.5t",
    jumpPower: "33m", runSpeed: "100m/5.7s",
    humanHost: "剑崎一真", homePlanet: "地球",
    transformationItem: "Blay带扣+Blay卡组",
    color: "#3366ff", colorSecondary: "#c0c0c0",
    abilities: ["Lightning Blast", "King Form", "Jack Form", "金属化装甲", "卡片封印"],
    description: `假面骑士Blade是卡片对战系统骑士。剑崎一真是BOARD组织的骑士，使用卡片封印不死者Undead。通过觉醒融合系统可进化为Jack Form和King Form。最终形态时与Joker融合。`,
    story: `一万年前的不死者战争在万年后的现代重新开启。BOARD组织开发了骑士系统，剑崎一真被选中为假面骑士Blade。随着战斗的推进，剑崎不断融合不死者的力量，从普通形态到Jack Form，再到King Form。命运中，他的友人也变成了Joker。为了拯救世界，剑崎做出了巨大的牺牲。`
  },
  {
    id: 17, name: "假面骑士响鬼", nameEn: "Kamen Rider Hibiki", category: "heisei",
    era: "平成 · 2005", debut: 2005,
    height: "222cm", weight: "156kg",
    punchPower: "20t", kickPower: "40t",
    jumpPower: "75m", runSpeed: "100m/3.0s",
    humanHost: "日高仁志", homePlanet: "地球",
    transformationItem: "音叉+变身鼓",
    color: "#9933cc", colorSecondary: "#ffcc00",
    abilities: ["音击打·火炎连打", "音击棒·烈火", "太鼓之达人", "Kurenai形态", "装甲响鬼"],
    description: `假面骑士响鬼以鬼和音乐为主题，是系列中风格最独特的作品之一。日高仁志是修炼音击的鬼战士，通过太鼓和音叉施展音击攻击，使用和风武器战斗。`,
    story: `日高仁志是一名音击战士，属于鬼之一族，通过修炼掌握了音击的力量。他使用太鼓作为武器，通过音波震慑并消灭魔化魍。响鬼的战斗不是改造人的产物，而是修炼的结果。他可以进化为红色的响鬼红，以及身披装甲的装甲响鬼。`
  },
  {
    id: 18, name: "假面骑士Kabuto", nameEn: "Kamen Rider Kabuto", category: "heisei",
    era: "平成 · 2006", debut: 2006,
    height: "195cm", weight: "95kg",
    punchPower: "3t", kickPower: "7t",
    jumpPower: "37m", runSpeed: "100m/5.8s",
    humanHost: "天道总司", homePlanet: "地球",
    transformationItem: "Kabuto Zecter",
    color: "#cc0000", colorSecondary: "#111111",
    abilities: ["Rider Kick", "Clock Up", "Hyper Form", "Hyper Clock Up", "Cast Off"],
    description: `假面骑士Kabuto以独角仙为原型，拥有Clock Up超高速能力。天道总司是一个被称为行天之道的男人，自称我是世界的中心。以绝对自信和强大战斗力著称。`,
    story: `1999年，一颗陨石坠落在涩谷，带来了外星生物Worm。天道总司在七年前获得了Kabuto Zecter，成为最强的战士。Kabuto可以通过Cast Off蜕变为Rider Form，发动Clock Up以超高速移动。Hyper Form更是可以穿梭时空。天道总司那句奶奶说过的台词成为了经典。`
  },
  {
    id: 19, name: "假面骑士电王", nameEn: "Kamen Rider Den-O", category: "heisei",
    era: "平成 · 2007", debut: 2007,
    height: "190cm", weight: "87kg",
    punchPower: "5t", kickPower: "7t",
    jumpPower: "35m", runSpeed: "100m/5.2s",
    humanHost: "野上良太郎", homePlanet: "地球",
    transformationItem: "电王腰带+骑士车票",
    color: "#33cc33", colorSecondary: "#ffcc00",
    abilities: ["电车斩", "形态切换", "Climax Form", "Liner Form", "时间穿越"],
    description: `假面骑士电王以时间旅行和电车为主题，是系列中最具人气的作品之一。史上最弱的变身者野上良太郎，与四个异魔神伙伴一同战斗，创造了独特的幽默风格。`,
    story: `天生倒霉的少年野上良太郎，偶然遇到了来自未来的异魔神桃塔罗斯。四个异魔神——桃塔罗斯、浦塔罗斯、金塔罗斯、龙塔罗斯附身在良太郎身上，使他可以变身电王。每个异魔神对应一个形态：剑形态、杖形态、斧形态、枪形态。不同异魔神切换时，人格也会切换，带来无穷的喜剧效果。`
  },
  {
    id: 20, name: "假面骑士Kiva", nameEn: "Kamen Rider Kiva", category: "heisei",
    era: "平成 · 2008", debut: 2008,
    height: "200cm", weight: "98kg",
    punchPower: "6t", kickPower: "8t",
    jumpPower: "85m", runSpeed: "100m/5.5s",
    humanHost: "红渡", homePlanet: "地球",
    transformationItem: "Kivat腰带",
    color: "#cc0000", colorSecondary: "#ffcc00",
    abilities: ["Darkness Moon Break", "Garulu Saber", "Bashaa Magnum", "Dogga Hammer", "Emperor Form"],
    description: `假面骑士Kiva以吸血鬼为主题，采用双时间线叙事。红渡是一个不善社交的青年，在战斗中以小提琴奏响旋律。可以召唤三种武器兽，最终形态为飞翔形态Emperor Form。`,
    story: `Kiva的故事在两条时间线中展开：1986年，红渡的父亲红音也是对抗Fangire的战士；2008年，红渡继承了Kiva的力量。被Kivat蝙蝠三世咬后可以变身，通过笛哨召唤三种武器兽。Kiva的Emperor Form身披红色斗篷，战斗力达到巅峰。剧中的父辈爱情线与子辈战斗线交织。`
  },
  {
    id: 21, name: "假面骑士Decade", nameEn: "Kamen Rider Decade", category: "heisei",
    era: "平成 · 2009", debut: 2009,
    height: "192cm", weight: "83kg",
    punchPower: "4t", kickPower: "8t",
    jumpPower: "25m", runSpeed: "100m/5.0s",
    humanHost: "门矢士", homePlanet: "地球（?）",
    transformationItem: "DecaDriver+Rider Cards",
    color: "#ff00ff", colorSecondary: "#111111",
    abilities: ["Dimension Kick", "KamenRide变身", "Complete Form", "Final Form Rides", "穿梭世界"],
    description: `假面骑士Decade是平成十周年纪念骑士。门矢士是一位穿梭各个骑士世界的破坏者。他可以使用KamenRide卡变身成其他假面骑士，最终形态Complete Form可召唤所有平成骑士。`,
    story: `门矢士失去了记忆，只知道自己是一个摄影师，也是世界的破坏者Decade。为了阻止世界融合，他踏上了穿越9个平行骑士世界的旅程。Decade可以变身为任何一位平成骑士，也能使用Final Form Rides将其他骑士化为武器。Complete Form胸前的卡片可以同时召唤所有平成骑士发动终极攻击。`
  },
  {
    id: 22, name: "假面骑士W", nameEn: "Kamen Rider Double", category: "heisei",
    era: "平成 · 2009", debut: 2009,
    height: "195cm", weight: "85kg",
    punchPower: "2.5t", kickPower: "6t",
    jumpPower: "60m", runSpeed: "100m/4.5s",
    humanHost: "左翔太郎 & 菲利普", homePlanet: "地球",
    transformationItem: "Double Driver+盖亚记忆体",
    color: "#33cc33", colorSecondary: "#111111",
    abilities: ["Joker Extreme", "Cyclone Effect", "记忆体切换", "Fang Joker", "Extreme Form"],
    description: `假面骑士W是二人一体的侦探骑士。左翔太郎和菲利普通过变身腰带合体，一人控制右边身体，一人控制左边身体。以侦探事务所为据点，守护风都的和平。`,
    story: `在风之都风都，私家侦探左翔太郎与神秘少年菲利普组成了二人一体的假面骑士W。使用盖亚记忆体变身，翔太郎控制身体右侧，菲利普控制左侧。三种身体记忆体和六种灵魂记忆体可组合出多种形态。当两人心意相通时，终极形态Cyclone Joker Extreme诞生。W的故事充满了硬汉侦探风格。`
  },
  {
    id: 23, name: "假面骑士OOO", nameEn: "Kamen Rider OOO", category: "heisei",
    era: "平成 · 2010", debut: 2010,
    height: "194cm", weight: "86kg",
    punchPower: "4.5t", kickPower: "12t",
    jumpPower: "190m", runSpeed: "100m/3.5s",
    humanHost: "火野映司", homePlanet: "地球",
    transformationItem: "OOO Driver+核心硬币",
    color: "#33cc33", colorSecondary: "#ffcc00",
    abilities: ["TaToBa Kick", "硬币切换", "恐龙联组", "超级TaToBa", "真OOO"],
    description: `假面骑士OOO以硬币和欲望为主题。火野映司是一个无欲无求的旅行者，意外获得了OOO腰带。使用鹰、虎、蝗虫三种核心硬币变身，可组合出数百种形态。`,
    story: `800年前，炼金术师创造了人造生命体Greeed和OOO系统。现代，旅行者火野映司成为了OOO的变身者。三枚核心硬币（Taka、Tora、Batta）组成基础形态TaToBa Combo。每种同色硬币组合产生Combo形态，如红色全鸟联组、蓝色全水联组等。终极形态恐龙联组拥有冻结时间的可怕力量。`
  },
  {
    id: 24, name: "假面骑士Fourze", nameEn: "Kamen Rider Fourze", category: "heisei",
    era: "平成 · 2011", debut: 2011,
    height: "200cm", weight: "95kg",
    punchPower: "3.5t", kickPower: "7.3t",
    jumpPower: "27m", runSpeed: "100m/5.0s",
    humanHost: "如月弦太朗", homePlanet: "地球",
    transformationItem: "Fourze Driver+天文开关",
    color: "#ffffff", colorSecondary: "#ff6600",
    abilities: ["Rider Rocket Punch", "Drill Kick", "Astro Switch切换", "Cosmic States", "宇宙之力"],
    description: `假面骑士Fourze以宇宙和青春校园为主题。转校生如月弦太朗在月球上获得Fourze腰带，使用天文开关变身为火箭头骑士。口号是宇宙来了！，与全校同学交朋友。`,
    story: `热血转校生如月弦太朗转学到天之川高中，在月球基地上遇到了Fourze系统。Fourze拥有40个天文开关，分别安装在四肢上：1号火箭开关、3号钻头开关等。形态从基本态到电力态、火焰态、磁力态，最终形态为能够使用全部开关的Cosmic States。弦太朗的口号要和所有人做朋友贯穿全剧。`
  },
  {
    id: 25, name: "假面骑士Wizard", nameEn: "Kamen Rider Wizard", category: "heisei",
    era: "平成 · 2012", debut: 2012,
    height: "198cm", weight: "90kg",
    punchPower: "4.5t", kickPower: "7.3t",
    jumpPower: "35m", runSpeed: "100m/5.0s",
    humanHost: "操真晴人", homePlanet: "地球",
    transformationItem: "Wizard Driver+魔法戒指",
    color: "#cc0000", colorSecondary: "#111111",
    abilities: ["Strike Wizard", "魔法戒指切换", "Dragon形态", "Infinity Style", "希望之力"],
    description: `假面骑士Wizard以魔法为主题。操真晴人是一个魔法使，使用魔法戒指变身。火、水、风、土四种元素形态加上龙之力量，以及最终的Infinity钻石形态。`,
    story: `在一场仪式中，操真晴人成为了幸存者，获得了魔法使的力量。使用Wizard Driver和魔法戒指变身火焰形态，通过切换戒指可以使用水流、飓风、大地等不同元素形态。当龙之力觉醒时可以获得更强的Dragon形态。最终形态Infinity Style使用钻石魔法，闪耀无比。Wizard的主题是绝望与希望。`
  },
  {
    id: 26, name: "假面骑士铠武", nameEn: "Kamen Rider Gaim", category: "heisei",
    era: "平成 · 2013", debut: 2013,
    height: "203cm", weight: "105kg",
    punchPower: "6.7t", kickPower: "14.5t",
    jumpPower: "23m", runSpeed: "100m/5.9s",
    humanHost: "葛叶纮汰", homePlanet: "地球",
    transformationItem: "战极驱动器+定锁种子",
    color: "#ff6600", colorSecondary: "#3366ff",
    abilities: ["大橙丸斩击", "Kiwami Arms", "Jimber Arms", "Kachidoki Arms", "黄金果实之力"],
    description: `假面骑士铠武以战国武将和水果为主题。葛叶纮汰是街舞团体的成员，通过定锁种子变身为铠武。从Orange Arms到Jimber Arms，再到最终的Kiwami Arms（极铠甲）。`,
    story: `在沢芽市，年轻人通过异世界赫尔海姆森林的果实获得了变身力量。葛叶纮汰获得了Orange定锁种子，变身为假面骑士铠武。随着对异世界真相的揭开，纮汰不断面对艰难的抉择。最终形态极铠甲可以使用所有骑士的武器。铠武以水果铠甲和战国武将的设定，讲述了一个关于力量与责任的史诗故事。`
  },
  {
    id: 27, name: "假面骑士Drive", nameEn: "Kamen Rider Drive", category: "heisei",
    era: "平成 · 2014", debut: 2014,
    height: "199cm", weight: "102kg",
    punchPower: "6t", kickPower: "12t",
    jumpPower: "35m", runSpeed: "100m/3.2s",
    humanHost: "泊进之介", homePlanet: "地球",
    transformationItem: "Drive Driver+Shift Cars",
    color: "#cc0000", colorSecondary: "#111111",
    abilities: ["SpeeDrop", "Shift Car切换", "Type Dead Heat", "Type Formula", "Type Tridoron"],
    description: `假面骑士Drive以汽车和警察为主题。警官泊进之介搭档腰带先生（Krim Steinbelt），使用Shift Cars变身。从Type Speed到Type Formula，最终形态为Tridoron。`,
    story: `全球冻结事件后，机械生命体Roidmude开始在暗中活动。警官泊进之介被搭档腰带先生选中，成为假面骑士Drive。Drive使用Shift Cars作为变身道具，形态命名以汽车类型为参考：速度型、野性型、技术型等。最终形态Type Tridoron融合了全部Shift Cars的力量，加上Formula型的方程式赛车速度。`
  },
  {
    id: 28, name: "假面骑士Ghost", nameEn: "Kamen Rider Ghost", category: "heisei",
    era: "平成 · 2015", debut: 2015,
    height: "204cm", weight: "96kg",
    punchPower: "6.5t", kickPower: "13t",
    jumpPower: "42m", runSpeed: "100m/4.2s",
    humanHost: "天空寺尊", homePlanet: "地球",
    transformationItem: "Ghost Driver+幽灵眼魂",
    color: "#ff6600", colorSecondary: "#111111",
    abilities: ["Omega Drive", "伟人魂切换", "Grateful魂", "Mugen魂", "无限进化"],
    description: `假面骑士Ghost以幽灵和历史伟人为主题。天空寺尊在18岁生日被眼魔杀害，变成了幽灵。他需要在99天内收集15个幽灵眼魂才能复活。每个眼魂对应一位伟人。`,
    story: `天空寺尊是一名继承了幽灵猎人血脉的少年。在18岁生日当天被眼魔杀害，变成了幽灵。他必须在99天内收集15个幽灵眼魂才能完全复活。使用伟人眼魂可以变身对应的伟人形态：牛顿、武藏、爱迪生、比利小子、贝多芬等。最终形态Mugen魂拥有无限进化的力量。`
  },
  {
    id: 29, name: "假面骑士Ex-Aid", nameEn: "Kamen Rider Ex-Aid", category: "heisei",
    era: "平成 · 2016", debut: 2016,
    height: "205cm", weight: "97kg",
    punchPower: "5.7t", kickPower: "10.2t",
    jumpPower: "30m", runSpeed: "100m/4.5s",
    humanHost: "宝生永梦", homePlanet: "地球",
    transformationItem: "Gamer Driver+Rider Gashat",
    color: "#ff00ff", colorSecondary: "#33cc33",
    abilities: ["Mighty Critical Strike", "Gashat切换", "无敌玩家", "Hyper Muteki", "游戏领域"],
    description: `假面骑士Ex-Aid以游戏和医生为主题。儿科实习医生宝生永梦是一个天才玩家，使用游戏卡带变身。形态按游戏类型分级，最终形态Hyper Muteki是无敌的黄金战士。`,
    story: `宝生永梦是圣都大学医院的儿科实习医生，同时是被誉为天才玩家M的传说级游戏玩家。当游戏病病毒开始在人类中传播，永梦成为了能够对抗病毒的假面骑士Ex-Aid。各类游戏卡带对应不同形态：动作游戏、射击游戏、格斗游戏、赛车游戏等。终极形态Hyper Muteki拥有无敌能力，任何攻击都无法伤害他。`
  },
  {
    id: 30, name: "假面骑士Build", nameEn: "Kamen Rider Build", category: "heisei",
    era: "平成 · 2017", debut: 2017,
    height: "196cm", weight: "99kg",
    punchPower: "9.9t", kickPower: "23.7t",
    jumpPower: "37m", runSpeed: "100m/3.0s",
    humanHost: "桐生战兔", homePlanet: "地球",
    transformationItem: "Build Driver+Full Bottles",
    color: "#cc0000", colorSecondary: "#3366ff",
    abilities: ["Vortex Finish", "Full Bottle切换", "Rabbit Tank Sparkling", "Genius Form", "公式之力"],
    description: `假面骑士Build以科学和实验为主题。失忆的天才物理学家桐生战兔使用Full Bottle变身。以兔子和坦克为基础形态，通过不同Full Bottle组合创造出各种形态。`,
    story: `火星探测器带回的潘多拉魔盒引发了天空之壁灾难，将日本一分为三。失忆的天才物理学家桐生战兔在石动惣一的指导下成为假面骑士Build。Build使用Full Bottle变身——兔子与坦克组成基础形态。最佳搭配Full Bottle有60种组合。最终形态Genius Form拥有所有Full Bottle的力量。Build探讨了正义与科学的边界。`
  },
  {
    id: 31, name: "假面骑士Zi-O", nameEn: "Kamen Rider Zi-O", category: "heisei",
    era: "平成 · 2018", debut: 2018,
    height: "200cm", weight: "92kg",
    punchPower: "8.2t", kickPower: "19t",
    jumpPower: "30m", runSpeed: "100m/3.8s",
    humanHost: "常磐庄吾", homePlanet: "地球",
    transformationItem: "Ziku Driver+Ride Watch",
    color: "#ff00ff", colorSecondary: "#ffcc00",
    abilities: ["Time Break", "Rider Armor", "Grand Zi-O", "Ohma Zi-O", "时间操控"],
    description: `假面骑士Zi-O是平成二十周年纪念骑士。高中生常磐庄吾注定成为未来的魔王逢魔Zi-O。他使用Ride Watch变身，可以借用历代假面骑士的力量。`,
    story: `常磐庄吾是一个梦想成为王的高中生。当未来的魔王逢魔Zi-O出现在他面前，庄吾得知了自己将成为毁灭世界的魔王的命运。但他决心改变这命运，成为最善良的魔王。Zi-O使用历代骑士的Ride Watch，可以变身为Armor形态继承前辈力量。最终形态Grand Zi-O拥有全部平成骑士之力。`
  },

  // ==================== 令和骑士 ====================
  {
    id: 32, name: "假面骑士Zero-One", nameEn: "Kamen Rider Zero-One", category: "reiwa",
    era: "令和 · 2019", debut: 2019,
    height: "196cm", weight: "87kg",
    punchPower: "8.4t", kickPower: "49.3t",
    jumpPower: "31.2m", runSpeed: "100m/4.1s",
    humanHost: "飞电或人", homePlanet: "地球",
    transformationItem: "Hiden Zero-One Driver+Progrise Key",
    color: "#33cc33", colorSecondary: "#ffff00",
    abilities: ["Rising Impact", "Progrise Key切换", "Shining Hopper", "Zero-Two", "AI预测"],
    description: `假面骑士Zero-One是令和骑士系列的首部作品。飞电或人是一位立志让人类和Humagear（AI机器人）和谐共存的搞笑艺人兼社长。以蝗虫为原型，致敬昭和前辈。`,
    story: `近未来世界，Humagear人工智能机器人与人类共存。飞电或人继承了祖父的飞电智能公司，成为了社长，同时也成为了假面骑士Zero-One。基础形态Rising Hopper的蝗虫主题致敬了假面骑士1号。Zero-One的形态包括各种动物和机械Progrise Key。最终形态Zero-Two拥有超越AI的思考和行动速度。`
  },
  {
    id: 33, name: "假面骑士Saber", nameEn: "Kamen Rider Saber", category: "reiwa",
    era: "令和 · 2020", debut: 2020,
    height: "217cm", weight: "98kg",
    punchPower: "11.5t", kickPower: "25.8t",
    jumpPower: "22.4m", runSpeed: "100m/4.0s",
    humanHost: "神山飞羽真", homePlanet: "地球",
    transformationItem: "圣剑Sword Driver+Wonder Ride Book",
    color: "#cc0000", colorSecondary: "#ffcc00",
    abilities: ["烈火拔刀", "Wonder Ride切换", "龙之骑士", "Crimson Saber", "Xross Saber"],
    description: `假面骑士Saber以圣剑和书为主题。小说家神山飞羽真使用火炎剑烈火和Wonder Ride Book变身。每个Wonder Ride Book都是一个故事，形态丰富多样。`,
    story: `小说家兼书店老板神山飞羽真，在童年时曾进入异世界Wonder World。长大后，他获得了火炎剑烈火和勇气之龙Wonder Ride Book，成为假面骑士Saber。Saber的世界中有多位剑士，每人拥有一把圣剑。飞羽真可以组合不同的Wonder Ride Book创造新形态。最终形态Xross Saber拥有全知全能的力量。`
  },
  {
    id: 34, name: "假面骑士Revice", nameEn: "Kamen Rider Revice", category: "reiwa",
    era: "令和 · 2021", debut: 2021,
    height: "199cm", weight: "92kg",
    punchPower: "15t", kickPower: "48t",
    jumpPower: "28.5m", runSpeed: "100m/3.4s",
    humanHost: "五十岚一辉", homePlanet: "地球",
    transformationItem: "Revice Driver+Vistamp",
    color: "#33cc33", colorSecondary: "#ff00ff",
    abilities: ["Revice Kick", "Remix变身", "Barid Rex", "Thunder Gale", "Ultimate Revice"],
    description: `假面骑士Revice以恶魔契约为主题。五十岚一辉与体内的恶魔Vice签订契约，二人一体变身。Vice作为实体化恶魔搭档，与一辉共同战斗。`,
    story: `五十岚家经营的澡堂幸福汤中，长子一辉与体内的恶魔Vice签订了契约。使用Vistamp印章变身，恐龙主题的Rex基因组为基础形态。Revice的特殊之处在于变身是一辉（Revi）和Vice（Vice）同时作为两个独立的战士战斗。一辉可以通过不同Vistamp借用前辈骑士的力量进行基因组切换。`
  },
  {
    id: 35, name: "假面骑士Geats", nameEn: "Kamen Rider Geats", category: "reiwa",
    era: "令和 · 2022", debut: 2022,
    height: "203cm", weight: "95kg",
    punchPower: "3.9t", kickPower: "11.7t",
    jumpPower: "78m", runSpeed: "100m/2.8s",
    humanHost: "浮世英寿", homePlanet: "地球",
    transformationItem: "Desire Driver+Raise Buckle",
    color: "#ffffff", colorSecondary: "#ff6600",
    abilities: ["Magnum Boost", "Raise Buckle切换", "Boostriker", "Geats IX", "愿望实现"],
    description: `假面骑士Geats以生存游戏和愿望实现为主题。浮世英寿是Desire Grand Prix大赛的常胜冠军。以白狐面具为标志，枪法与格斗技术一流，是战术大师。`,
    story: `Desire Grand Prix（欲望大奖赛）是一场神秘的生存游戏，胜者可以实现任何愿望。浮世英寿是大赛的不败传说，拥有数千年的参赛经验。Geats使用Raise Buckle进行形态变换：Magnum（枪械）、Boost（加速）、Monster（怪物）等。最终形态Geats IX融合了所有力量，以九尾狐的形态出现，拥有改写现实的力量。`
  },
  {
    id: 36, name: "假面骑士Gotchard", nameEn: "Kamen Rider Gotchard", category: "reiwa",
    era: "令和 · 2023", debut: 2023,
    height: "202cm", weight: "98kg",
    punchPower: "8.2t", kickPower: "15.8t",
    jumpPower: "32m", runSpeed: "100m/3.4s",
    humanHost: "一之濑宝太郎", homePlanet: "地球",
    transformationItem: "Gotchard Driver+Chemy Card",
    color: "#3366ff", colorSecondary: "#ff6600",
    abilities: ["Steam Hopper Kick", "Chemy融合", "Super Gotchard", "X Gotchard", "炼金术之力"],
    description: `假面骑士Gotchard以炼金术和卡片为主题。高中生一之濑宝太郎偶然获得Gotchard Driver并使用Chemy Cards变身。双卡片组合产生不同形态。`,
    story: `高中生一之濑宝太郎梦想成为一名炼金术师。当他偶然获得Gotchard Driver和蝗虫、蒸汽火车两张Chemy Cards后，可以变身为Steam Hopper形态。Gotchard通过组合不同的Chemy Cards创造新形态，已经有101种Chemy生物等待被收集。超级Gotchard和X Gotchard是更强大的进阶形态。`
  },

  // 额外传奇骑士
  {
    id: 37, name: "假面骑士真", nameEn: "Shin Kamen Rider", category: "showa",
    era: "昭和 · 1992", debut: 1992,
    height: "182cm", weight: "76kg",
    punchPower: "70t", kickPower: "110t",
    jumpPower: "100m", runSpeed: "100m/1.8s",
    humanHost: "风祭真", homePlanet: "地球",
    transformationItem: "生化改造",
    color: "#111111", colorSecondary: "#cc0000",
    abilities: ["真Rider Kick", "生化盔甲", "高跳跃力", "怪力攻击", "自愈能力"],
    description: `假面骑士真是1992年推出的真·假面骑士电影版主角。以写实的生化改造人形象呈现，风格更加黑暗成熟。风祭真是被改造的生化战士，敌人同样拥有恐怖的外形。`,
    story: `风祭真被邪恶组织改造为生化士兵。这个版本的假面骑士更具写实感和恐怖感，生化改造使他可以迅速自愈伤口，弹跳力惊人。真·假面骑士是石之森章太郎原案中追求的真正的假面骑士形象，更具生物性和悲剧色彩。`
  },
  {
    id: 38, name: "假面骑士ZO", nameEn: "Kamen Rider ZO", category: "showa",
    era: "昭和 · 1993", debut: 1993,
    height: "193cm", weight: "83kg",
    punchPower: "80t", kickPower: "120t",
    jumpPower: "80m", runSpeed: "100m/1.5s",
    humanHost: "麻生胜", homePlanet: "地球",
    transformationItem: "生化腰带",
    color: "#33cc33", colorSecondary: "#c0c0c0",
    abilities: ["ZO Kick", "生化重组", "蝗虫基因", "超速移动", "细胞再生"],
    description: `假面骑士ZO是1993年的剧场版骑士。麻生胜被新生命体改造为完美的生化战士ZO，拥有蝗虫的基因。身体可以自由重组，具有极强的再生能力。`,
    story: `麻生胜被疯狂科学家望月博士改造为生化战士ZO。融合了蝗虫基因的ZO拥有超强的运动能力和自愈力。这部作品采用了当时最先进的CG特效和皮套技术，是假面骑士迈向新世纪的里程碑作品。`
  },
  {
    id: 39, name: "假面骑士J", nameEn: "Kamen Rider J", category: "showa",
    era: "昭和 · 1994", debut: 1994,
    height: "194cm (最大40m)", weight: "84kg",
    punchPower: "90t", kickPower: "130t",
    jumpPower: "100m", runSpeed: "100m/1.2s",
    humanHost: "濑川元气", homePlanet: "地球",
    transformationItem: "J-Spirit",
    color: "#33cc33", colorSecondary: "#cc0000",
    abilities: ["J Kick", "巨大化", "J-Jumbo", "大地之力", "蝗虫跳跃"],
    description: `假面骑士J是昭和时代最后一位骑士。濑川元气被地底人Earth Spirits改造为守护大地的战士。J的最大特色是可以巨大化到40米，与巨型怪物进行等身战斗。`,
    story: `濑川元气是保护地球生态的记者，被地底人选中接受改造。J可以从1.94米巨大化到40米，这在假面骑士中极为罕见。巨大化后可以正面与超大型怪兽战斗。J的故事融合了环保主题和巨大英雄元素。`
  },
  {
    id: 40, name: "假面骑士G3", nameEn: "Kamen Rider G3", category: "heisei",
    era: "平成 · 2001", debut: 2001,
    height: "192cm", weight: "150kg",
    punchPower: "1t", kickPower: "3t",
    jumpPower: "10m", runSpeed: "100m/8.0s",
    humanHost: "冰川诚", homePlanet: "地球",
    transformationItem: "G3装甲系统",
    color: "#3366ff", colorSecondary: "#c0c0c0",
    abilities: ["G3机枪", "G3火箭弹", "G3-X强化", "警察格斗术", "科学搜查"],
    description: `假面骑士G3是人类制造的纯机械骑士装甲。冰川诚是警视厅的精英刑警，穿着G3装甲与未知生命体战斗。与AgitΩ不同，G3是纯粹的科学结晶。`,
    story: `在未确认生命体事件后，警视厅开发了G3装甲系统，由人类精英刑警冰川诚着装。G3没有超能力，依靠装甲、武器和训练进行战斗。后期升级为G3-X，增加了AI辅助战斗系统。G3代表了人类以科技挑战超自然力量的意志。`
  },
  {
    id: 41, name: "假面骑士Cross-Z", nameEn: "Kamen Rider Cross-Z", category: "heisei",
    era: "平成 · 2017", debut: 2017,
    height: "197cm", weight: "102kg",
    punchPower: "23.5t", kickPower: "45.4t",
    jumpPower: "45m", runSpeed: "100m/2.0s",
    humanHost: "万丈龙我", homePlanet: "地球",
    transformationItem: "Build Driver+Dragon Full Bottle",
    color: "#3366ff", colorSecondary: "#ffcc00",
    abilities: ["Dragonic Finish", "Cross-Z Charge", "Great Cross-Z", "Cross-Z Magma", "龙之力"],
    description: `假面骑士Cross-Z是Build的二号骑士。前格斗家万丈龙我以龙之Full Bottle变身，以近战格斗为主要战斗方式。与Build构成了平成后期的经典双骑士组合。`,
    story: `万丈龙我是被诬陷入狱的前格斗家，逃狱后遇到桐生战兔成为假面骑士Cross-Z。使用龙Full Bottle可以发挥惊人的格斗力量。Cross-Z Charge形态装备龙之铁拳，Great Cross-Z形态更加华丽。最终形态Cross-Z Magma的体温可以飙升到熔化一切的程度。`
  }
];

// Bilibili video mapping for each rider
const riderVideos = {
  1: { bvid: "BV12c7F6WEZb", title: "假面骑士变身合集1971-2026 · 全骑士收录" },
  2: { bvid: "BV12c7F6WEZb", title: "假面骑士变身合集1971-2026 · 全骑士收录" },
  3: { bvid: "BV12c7F6WEZb", title: "假面骑士变身合集1971-2026 · 全骑士收录" },
  4: { bvid: "BV1J4411C7wZ", title: "假面骑士X剧场版 五骑士对黑暗之王 战斗合集" },
  5: { bvid: "BV1jqLRz6EV7", title: "假面骑士亚马逊（1974）" },
  6: { bvid: "BV1rb421E7gq", title: "假面骑士Stronger 全集解说" },
  7: { bvid: "BV1inTp6kEMd", title: "假面骑士Skyrider 战斗精选" },
  8: { bvid: "BV1yt41167UE", title: "假面骑士Super-1 战斗插曲MV" },
  9: { bvid: "BV1AJ411P7PM", title: "假面骑士ZX 战斗合集" },
  10: { bvid: "BV1Hr421L7sH", title: "假面骑士Black 1080p全集" },
  11: { bvid: "BV1nrTE6kEeN", title: "假面骑士Black RX 4K战斗合集" },
  12: { bvid: "BV1MWEu6WECa", title: "假面骑士空我 TV49话+SP 全51话" },
  13: { bvid: "BV12c7F6WEZb", title: "假面骑士变身合集1971-2026 · 全骑士收录" },
  14: { bvid: "BV1Gu4y1h7zd", title: "假面骑士龙骑 全集解说" },
  15: { bvid: "BV1bW411h7b6", title: "假面骑士Faiz 555 战斗合集" },
  16: { bvid: "BV1DZ4y1k7AQ", title: "假面骑士Blade 超全集 4K" },
  17: { bvid: "BV12c7F6WEZb", title: "假面骑士变身合集1971-2026 · 全骑士收录" },
  18: { bvid: "BV14L41157jt", title: "假面骑士Kabuto 变身音效合集" },
  19: { bvid: "BV1oS4y117kS", title: "假面骑士电王 TV全集+剧场版 [1080p]" },
  20: { bvid: "BV1S54y137rm", title: "假面骑士Kiva 4K全形态变身合集" },
  21: { bvid: "BV1xJ41177SH", title: "假面骑士Decade 超全集" },
  22: { bvid: "BV1ckrSYXEkm", title: "假面骑士W 完结篇" },
  23: { bvid: "BV1wwVZ6NErD", title: "假面骑士OOO TV48话全" },
  24: { bvid: "BV12c7F6WEZb", title: "假面骑士变身合集1971-2026 · 全骑士收录" },
  25: { bvid: "BV1emySBzEcq", title: "假面骑士Wizard 全集 2K 完结" },
  26: { bvid: "BV1CG411s7Zi", title: "假面骑士铠武 变身音效合集" },
  27: { bvid: "BV1wP4y1u7zk", title: "假面骑士Drive 超全集" },
  28: { bvid: "BV1hw4m1Y7m1", title: "假面骑士Ghost 战斗合集" },
  29: { bvid: "BV12c7F6WEZb", title: "假面骑士变身合集1971-2026 · 全骑士收录" },
  30: { bvid: "BV1sc7X6NEaF", title: "假面骑士Build 4K全集" },
  31: { bvid: "BV1epMJzmEci", title: "假面骑士Zi-O 4K全形态变身合集" },
  32: { bvid: "BV1odxKzbEEU", title: "假面骑士Zero-One 合集" },
  33: { bvid: "BV1944y1a7pN", title: "假面骑士Saber 超全集 4K" },
  34: { bvid: "BV1EB4y1i7sR", title: "假面骑士Revice 完结" },
  35: { bvid: "BV1bv4y1X7bg", title: "假面骑士Geats OST合集" },
  36: { bvid: "BV1DYkqYPEMS", title: "假面骑士Gotchard 音效合集" },
  37: { bvid: "BV1hx2LByEeH", title: "假面骑士Gavv 4K全形态变身合集" },
  38: { bvid: "BV1E84y1X7vX", title: "假面骑士 真 ZO J 怪人合集" },
  39: { bvid: "BV1ro4y1f7jV", title: "假面骑士J & ZO 合集" },
  40: { bvid: "BV12c7F6WEZb", title: "假面骑士变身合集1971-2026 · 全骑士收录" },
  41: { bvid: "BV1jt411K7uG", title: "假面骑士Cross-Z 战斗特辑" },
};
